package com.hazem.worklink.models.enums;

public enum NotificationType {
    WELCOME,
    APPLICATION_SUBMITTED,
    APPLICATION_ACCEPTED,
    APPLICATION_REJECTED,
    APPLICATION_WITHDRAWN,
    NEW_MISSION_MATCH,
    MISSION_DEADLINE_SOON,
    PROFILE_INCOMPLETE
}
