package com.hazem.worklink.models.enums;

public enum ReportType {
    FRAUDE,
    COMPORTEMENT,
    PAIEMENT,
    DOCUMENT_FALSIFIE,
    HORS_SUJET,
    BUG_TECHNIQUE,
    PROBLEME_NOTIFICATION,
    PROBLEME_MESSAGERIE,
    ACCES_FONCTIONNALITE,
    CONTENU_INAPPROPRIE,
    COMPTE_INJUSTE,
    AUTRE
}
